# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2        
    - name: Get current UTC time
      id: date
      run: echo "::set-output name=date::$(TZ='UTC' date +'.%Y%m%d.%H%M%S')"
    - name: Update pom version
      run: 
        sed -i s/-SNAPSHOT/${{steps.date.outputs.date}}/g pom.xml
    - name: Build with Maven      
      run: mvn -B install --file pom.xml
    - name: Publish to GitHub Packages Apache Maven 
      env:
        GITHUB_TOKEN: ${{ github.token }} # GITHUB_TOKEN is the default env for the password
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
    - name: Copy build artifact
      run: mkdir staging && cp target/*-jar-with-dependencies.jar staging
    - name: Upload fat jar      
      uses: actions/upload-artifact@v1
      with:
        name: ExecutableJar
        path: staging
